### ISSUE TITLE
allow for roundtripping of structured_patterns using inner keys

### ISSUE THREAD

**Issue by cmungall** [linkml/schemasheets#72]
given a schema

```yaml
classes:
  Person:
    attributes:
      first:
      last:
      full:
        structured_pattern:
          syntax: "{token} {token}"
```

we'd like a header column of:

```
structured_pattern
> inner_key: syntax
```

such that flat values like "{token} {token}" can be used in the datafile

This *should* work but an exception is currently thrown

discovered by @turbomam
